-- Table for student biodata update approvals
CREATE TABLE biodata_update_approvals (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    nama_baru VARCHAR(100),
    nis_baru VARCHAR(20),
    nisn_baru VARCHAR(20),
    kelas_baru VARCHAR(50),
    jurusan_baru ENUM('TKJ', 'TO', 'DPIB'),
    grha_baru VARCHAR(50),
    nama_lama VARCHAR(100),
    nis_lama VARCHAR(20),
    nisn_lama VARCHAR(20),
    kelas_lama VARCHAR(50),
    jurusan_lama ENUM('TKJ', 'TO', 'DPIB'),
    grha_lama VARCHAR(50),
    requested_by INT NOT NULL,
    pembina_status ENUM('pending', 'approved', 'rejected') DEFAULT 'pending',
    superadmin_status ENUM('pending', 'approved', 'rejected') DEFAULT 'pending',
    pembina_notes TEXT,
    superadmin_notes TEXT,
    pembina_approved_at TIMESTAMP NULL,
    superadmin_approved_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (requested_by) REFERENCES users(id) ON DELETE CASCADE
);
